#!/usr/bin/env bash

## Description: Override the nginx conf by a specific one
## Usage: nginx-config <conf_file>
## <conf_file>: Relative path from the .ddev folder
## Example: "ddev nginx-config custom_files/custom-nginx-site.conf"


CURRENT_DIR=${PWD##*/}

if [ "$CURRENT_DIR" != ".ddev" ];
then
  echo "This script must be run in a .ddev directory"
  echo "We are here: ${CURRENT_DIR}"
  exit 1
fi


FILEPATH=${1:-default}

if [ "$FILEPATH" == "default" ];
then
    echo "File path is mandatory"
    exit 1
fi

ddev exec cp /etc/nginx/sites-enabled/nginx-site.conf /etc/nginx/sites-enabled/nginx-site.conf.backup
docker cp "$FILEPATH" ddev-"${DDEV_SITENAME}"-web://etc/nginx/sites-enabled/nginx-site.conf
ddev exec nginx -t
ddev exec nginx -s reload
echo "Nginx config has been modified"
echo "To use the original conf, please run a ddev restart"



