#!/usr/bin/env bash

## Description: Run Magento 2 cron on every minute
## Usage: cron command
## Example: "ddev cron"

while true
do
  echo "Start: `date -u`" >> /var/www/html/var/log/magento.cron.log
  /usr/bin/php /var/www/html/bin/magento cron:run >> /var/www/html/var/log/magento.cron.log
  echo "End: `date -u`" >> /var/www/html/var/log/magento.cron.log
  sleep 60
done
