#!/usr/bin/env bash

## Description: Run PHPCS for some folder
## Usage: phpcs folder
## Example: "ddev phpcs my-own-modules/my-module"


/usr/bin/php ./vendor/bin/phpcs  --standard=Magento2 --runtime-set ignore_errors_on_exit 1 --runtime-set ignore_warnings_on_exit 1 $@
