#!/usr/bin/env bash

## Description: Run PHPCBF for some folder
## Usage: phpcbf folder
## Example: "ddev phpcbf my-own-modules/my-module"


/usr/bin/php ./vendor/bin/phpcbf  --standard=Magento2 --runtime-set ignore_errors_on_exit 1 --runtime-set ignore_warnings_on_exit 1  $@
